/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
const sidebars = {
  networkSidebar: [
    {
      type: "link",
      label: "Status",
      href: "https://linea.statuspage.io/",
      className: "sidebar-status-link",
    },
    {
      type: "link",
      label: "Bridge",
      href: "https://bridge.linea.build",
      className: "sidebar-bridge-link",
    },
    {
      type: "autogenerated",
      dirName: "network",
    },
  ],
  apiSidebar: [
    {
      type: "autogenerated",
      dirName: "api",
    },
  ],
  protocolSidebar: [
    {
      type: "autogenerated",
      dirName: "protocol",
    },
  ],
  stackSidebar: [
    {
      type: "autogenerated",
      dirName: "stack",
    },
  ],
  changelogSidebar: [
    {
      type: "autogenerated",
      dirName: "changelog",
    },
  ],
};

module.exports = sidebars;
